
package elead.service.ts;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiceTimesheetService", targetNamespace = "http://ts.service.elead/", wsdlLocation = "http://202.105.98.214:9001/Service/Timesheet?wsdl")
public class ServiceTimesheetService
    extends Service
{

    private final static URL SERVICETIMESHEETSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(elead.service.ts.ServiceTimesheetService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = elead.service.ts.ServiceTimesheetService.class.getResource(".");
            url = new URL(baseUrl, "http://202.105.98.214:9001/Service/Timesheet?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://202.105.98.214:9001/Service/Timesheet?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICETIMESHEETSERVICE_WSDL_LOCATION = url;
    }

    public ServiceTimesheetService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceTimesheetService() {
        super(SERVICETIMESHEETSERVICE_WSDL_LOCATION, new QName("http://ts.service.elead/", "ServiceTimesheetService"));
    }

    /**
     * 
     * @return
     *     returns ServiceTimesheet
     */
    @WebEndpoint(name = "ServiceTimesheetPort")
    public ServiceTimesheet getServiceTimesheetPort() {
        return super.getPort(new QName("http://ts.service.elead/", "ServiceTimesheetPort"), ServiceTimesheet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceTimesheet
     */
    @WebEndpoint(name = "ServiceTimesheetPort")
    public ServiceTimesheet getServiceTimesheetPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ts.service.elead/", "ServiceTimesheetPort"), ServiceTimesheet.class, features);
    }

}
