
package elead.service.ts;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceTimesheet", targetNamespace = "http://ts.service.elead/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceTimesheet {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "promoteTS", targetNamespace = "http://ts.service.elead/", className = "elead.service.ts.PromoteTS")
    @ResponseWrapper(localName = "promoteTSResponse", targetNamespace = "http://ts.service.elead/", className = "elead.service.ts.PromoteTSResponse")
    public String promoteTS(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Timesheet> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
